version: "3.8"
name: "rinha"

services:
  api1:
    build: .
    container_name: "application_1"
    hostname: api1
    environment:
      - SERVER_PORT=8080
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: '1.25GB'
    networks:
      - rinha-network

  api2:
    build: .
    container_name: "application_2"
    hostname: ap12
    environment:
      - SERVER_PORT=8080
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: '1.25GB'
    networks:
      - rinha-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '0.25GB'

networks:
  rinha-network:


