version: "3.8"
name: "rinha"

services:
  api1: &api
    build: .
    container_name: "api1"
    hostname: api1
    environment:
      - SERVER_PORT=8080
      - DATABASE_URL=jdbc:postgresql://db:5432/rinha
      - DATABASE_USER=user
      - DATABASE_PASS=secret
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.55'
          memory: '0.8GB'
    depends_on:
      - db
    networks:
      - app-network

  api2:
    <<: *api
    container_name: "api2"
    hostname: api2

  nginx:
    image: nginx:latest
    container_name: "nginx"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.2GB'
    networks:
      - app-network

  db:
    image: postgres:latest
    container_name: "db"
    command: postgres -c 'max_connections=465'
    environment:
      - POSTGRES_DB=rinha
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '1.1GB'
    networks:
      - app-network

networks:
  app-network: