version: "3.8"
name: "rinha"

services:
  api1: &api
    build: .
    container_name: "application_1"
    hostname: api1
    environment:
      - SERVER_PORT=8080
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1.35GB'

  api2:
    <<: *api
    container_name: "application_2"
    hostname: api2

  nginx:
    image: nginx:latest
    container_name: "nginx"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '0.3GB'