server:
  port: ${SERVER_PORT:8080}
  compression:
    enabled: true
    min-response-size: 1024
  tomcat:
    connection-timeout: 120000
    max-connections: 1000

spring:
  datasource:
    url: jdbc:h2:mem:test;IGNORECASE=TRUE
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
  mvc:
    async:
      request-timeout: 600000