server:
  port: ${SERVER_PORT:8080}
  compression:
    enabled: true
    min-response-size: 1024
  tomcat:
    connection-timeout: 120000
    max-connections: 1000

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASS}

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    async:
      request-timeout: 600000
